### ISSUE TITLE
Keybindings seem different than described in paper

### ISSUE THREAD

**Issue by ch-sa** [autonomousvision/kitti360LabelTool#1]
Hi @yiyiliao,

great that you published and open sourced your annotation tool here. I was just a little confused about the key bindings, as they seem differently configured than described in the paper.

![grafik](https://user-images.githubusercontent.com/26072175/142773285-8d912c95-71d5-414a-bdd9-c2c6f1f1b6d9.png)

The paper says the `E` key switches to scaling, while the `R` key enables rotation mode. Yet in the software it seems to be implemented vice versa.

Also it was interesting seeing your approach as I implemented a similar software last year for labeling 3D bounding boxes in point clouds called [labelCloud](https://github.com/ch-sa/labelCloud). We also presented and published it in CAD21, maybe the [corresponding publication](https://arxiv.org/abs/2103.04970) is also of interest for you.

UPDATE:
* I added a pull request that fixes the issue. It should be ready to merge.

Best regards,

Christoph

**Comment by yiyiliao** [comment]
Hi @ch-sa, thanks a lot for pointing out the issue and for fixing it!

Thank you for your pointer to labelCloud as well. This looks quite relevant indeed.
